### ISSUE TITLE
Specify dimensions of encoder board

### ISSUE THREAD

**Issue by samuk** [rosmo-robot/Rosmo_ESC#10]
As discussed it makes sense to develop a small encoder board so that users can plug and play the encoders. It would be good if this encoder could be used in a variety of motors.

![AS5048A-D](https://user-images.githubusercontent.com/400875/147828100-d069c6b3-9152-4607-bbd5-0de1648a8e6d.jpg)

I suggest we stick broadly to the above dimensions, whilst noting that the [BGM220](http://www.dys.hk/product/BGM2208-70.html) has 16mm spacing for the screw holes, so two 'notches' in the left and right of the above dimensions would give compatibility?

There would be a 7mm wide, side entry [JST SHR-06-VS ](https://www.jst-mfg.com/product/detail_e.php?series=231) without flange specified for soldering to the SPI side. This would be positioned 'in reverse' with the cabling going over the encoder chip so that it could be used in a [2205](https://ae01.alicdn.com/kf/H5db205d3acb24197b1f93c58d5f370b9e.jpg)

**Comment by runger1101001** [comment]
Here a picture and 3D render:

<img width="366" alt="image" src="https://user-images.githubusercontent.com/7306964/147984001-c4c0c69d-a605-484b-9718-d431d3b81f59.png">

![IMG_6523](https://user-images.githubusercontent.com/7306964/147984547-edd63272-a1f5-433b-aadd-49133d45a5d4.jpeg)

This is the pinout:

<img width="305" alt="image" src="https://user-images.githubusercontent.com/7306964/147983146-58b6e594-f3b2-43db-9943-f488bc9985e0.png">

These are the dimensions:

<img width="796" alt="image" src="https://user-images.githubusercontent.com/7306964/147986023-b112ab64-a2f5-4575-b254-69312046d97f.png">

**Comment by runger1101001** [comment]
If we can work with these for the prototype, then I have bunch here. I can provide AS5048As or TLE5012Bs in this shape.

If we want a different shape, we'd have to have some made :-)

**Comment by samuk** [comment]
Great! nice one..

**Comment by samuk** [comment]
These are now available here: https://www.tindie.com/products/smallrobots/as5048a-encoder-board-for-robots-motor-control/
